### ISSUE TITLE
I cannot see pvOptGUI in Paraview after loading the plugin

### ISSUE THREAD

**Issue by lj-cug** [DAFoam/pvOptGUI_tutorials#2]
I cannot see pvOptGUI in Paraview 5.9.0 after loading the plugin, both for Windows 64 and Ubuntu 20.04 OS. Now pvOptGUI plugin can be loaded normally, but no interface shows.

**Comment by friedenhe** [comment]
Please send screenshots of what you saw, which will help us identify the issue.

**Comment by lj-cug** [comment]
After loading pvOptGUI plugin, that shows as following:
![pvOptGUI-screen](https://github.com/DAFoam/pvOptGUI_tutorials/assets/53997605/a855faa4-8995-432e-a04a-d75f76a286a1)

I cannot see pvOptGUI at the left side.

**Comment by friedenhe** [comment]
It seems that you did not follow the exact steps from here: https://dafoam.github.io/mydoc_gui_pvoptairfoil.html#load-the-case-and-plugin. Please double-check.

**Comment by lj-cug** [comment]
Yes, it's OK now! In Sources, I see pvOptGUI. Thanks you.
